/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AboutView: typeof import('./src/components/AboutView.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Archive: typeof import('./src/components/Archive.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    MainNav: typeof import('./src/components/MainNav.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    NamedView: typeof import('./src/components/NamedView.vue')['default']
    NestedUserPost: typeof import('./src/components/NestedUserPost.vue')['default']
    NestedUserProfile: typeof import('./src/components/NestedUserProfile.vue')['default']
    NestedUserView: typeof import('./src/components/NestedUserView.vue')['default']
    NotFounds: typeof import('./src/components/NotFounds.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    ProfilePage: typeof import('./src/components/ProfilePage.vue')['default']
    RightNav: typeof import('./src/components/RightNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserEmailSubscriptions: typeof import('./src/components/UserEmailSubscriptions.vue')['default']
    UserPostsView: typeof import('./src/components/UserPostsView.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    UserProfilePreview: typeof import('./src/components/UserProfilePreview.vue')['default']
    UserSettings: typeof import('./src/components/UserSettings.vue')['default']
    UserSettingsNav: typeof import('./src/components/UserSettingsNav.vue')['default']
    UserView: typeof import('./src/components/UserView.vue')['default']
  }
}
