/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/DynamicComponent': RouteRecordInfo<'/DynamicComponent', '/DynamicComponent', Record<never, never>, Record<never, never>>,
    '/named': RouteRecordInfo<'/named', '/named', Record<never, never>, Record<never, never>, '/named/'>,
    '/named/': RouteRecordInfo<'/named/', '/named', Record<never, never>, Record<never, never>>,
    '/SimpleRouter': RouteRecordInfo<'/SimpleRouter', '/SimpleRouter', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>, '/users/' | '/users/[id]' | '/users/create1' | '/users/create2' | '/users/posts'>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]': RouteRecordInfo<'/users/[id]', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/create1': RouteRecordInfo<'/users/create1', '/users/create1', Record<never, never>, Record<never, never>>,
    '/users/create2': RouteRecordInfo<'/users/create2', '/users/create2', Record<never, never>, Record<never, never>>,
    '/users/posts': RouteRecordInfo<'/users/posts', '/users/posts', Record<never, never>, Record<never, never>>,
  }
}
