/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertBox: typeof import('./src/components/AlertBox.vue')['default']
    AppBarUnf: typeof import('./src/components/AppBarUnf.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BlogPost: typeof import('./src/components/BlogPost.vue')['default']
    BlogPostEmit: typeof import('./src/components/BlogPostEmit.vue')['default']
    CachedPropFunc: typeof import('./src/components/CachedPropFunc.vue')['default']
    ChildComp: typeof import('./src/components/ChildComp.vue')['default']
    ChildCompIn: typeof import('./src/components/ChildCompIn.vue')['default']
    ChildCompParam: typeof import('./src/components/ChildCompParam.vue')['default']
    ChildExpose: typeof import('./src/components/ChildExpose.vue')['default']
    ComputedProp: typeof import('./src/components/ComputedProp.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LifeCycleHookComp: typeof import('./src/components/LifeCycleHookComp.vue')['default']
    MainNavUnf: typeof import('./src/components/MainNavUnf.vue')['default']
    MyComponent: typeof import('./src/components/MyComponent.vue')['default']
    MyMultiComponent: typeof import('./src/components/MyMultiComponent.vue')['default']
    ParentCompIn: typeof import('./src/components/ParentCompIn.vue')['default']
    ProfilePageUnf: typeof import('./src/components/ProfilePageUnf.vue')['default']
    RightNavUnf: typeof import('./src/components/RightNavUnf.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VueList: typeof import('./src/components/VueList.vue')['default']
    WriteableComputed: typeof import('./src/components/WriteableComputed.vue')['default']
  }
}
