/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ArrayClassBind': RouteRecordInfo<'/ArrayClassBind', '/ArrayClassBind', Record<never, never>, Record<never, never>>,
    '/BlogPage': RouteRecordInfo<'/BlogPage', '/BlogPage', Record<never, never>, Record<never, never>>,
    '/BlogPageEmit': RouteRecordInfo<'/BlogPageEmit', '/BlogPageEmit', Record<never, never>, Record<never, never>>,
    '/BlogPageVFor': RouteRecordInfo<'/BlogPageVFor', '/BlogPageVFor', Record<never, never>, Record<never, never>>,
    '/CheckboxFormBind': RouteRecordInfo<'/CheckboxFormBind', '/CheckboxFormBind', Record<never, never>, Record<never, never>>,
    '/ClassBind': RouteRecordInfo<'/ClassBind', '/ClassBind', Record<never, never>, Record<never, never>>,
    '/ClassBindComponent': RouteRecordInfo<'/ClassBindComponent', '/ClassBindComponent', Record<never, never>, Record<never, never>>,
    '/ComponentRef': RouteRecordInfo<'/ComponentRef', '/ComponentRef', Record<never, never>, Record<never, never>>,
    '/ComponentSlot': RouteRecordInfo<'/ComponentSlot', '/ComponentSlot', Record<never, never>, Record<never, never>>,
    '/Instagram': RouteRecordInfo<'/Instagram', '/Instagram', Record<never, never>, Record<never, never>>,
    '/Parent': RouteRecordInfo<'/Parent', '/Parent', Record<never, never>, Record<never, never>>,
    '/ParentCompIn': RouteRecordInfo<'/ParentCompIn', '/ParentCompIn', Record<never, never>, Record<never, never>>,
    '/ParentCompParam': RouteRecordInfo<'/ParentCompParam', '/ParentCompParam', Record<never, never>, Record<never, never>>,
    '/RadioSelectedFormBind': RouteRecordInfo<'/RadioSelectedFormBind', '/RadioSelectedFormBind', Record<never, never>, Record<never, never>>,
    '/StyleBind': RouteRecordInfo<'/StyleBind', '/StyleBind', Record<never, never>, Record<never, never>>,
    '/TemplateRef': RouteRecordInfo<'/TemplateRef', '/TemplateRef', Record<never, never>, Record<never, never>>,
    '/TextFormBind': RouteRecordInfo<'/TextFormBind', '/TextFormBind', Record<never, never>, Record<never, never>>,
    '/VNumberInputs': RouteRecordInfo<'/VNumberInputs', '/VNumberInputs', Record<never, never>, Record<never, never>>,
    '/VTextFields': RouteRecordInfo<'/VTextFields', '/VTextFields', Record<never, never>, Record<never, never>>,
    '/YesNoQuestion': RouteRecordInfo<'/YesNoQuestion', '/YesNoQuestion', Record<never, never>, Record<never, never>>,
  }
}
