/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AppHeader': RouteRecordInfo<'/AppHeader', '/AppHeader', Record<never, never>, Record<never, never>>,
    '/FlexAlignContent': RouteRecordInfo<'/FlexAlignContent', '/FlexAlignContent', Record<never, never>, Record<never, never>>,
    '/FlexAlignItems': RouteRecordInfo<'/FlexAlignItems', '/FlexAlignItems', Record<never, never>, Record<never, never>>,
    '/FlexAlignSelf': RouteRecordInfo<'/FlexAlignSelf', '/FlexAlignSelf', Record<never, never>, Record<never, never>>,
    '/FlexBasis': RouteRecordInfo<'/FlexBasis', '/FlexBasis', Record<never, never>, Record<never, never>>,
    '/FlexDirection': RouteRecordInfo<'/FlexDirection', '/FlexDirection', Record<never, never>, Record<never, never>>,
    '/FlexDisplay': RouteRecordInfo<'/FlexDisplay', '/FlexDisplay', Record<never, never>, Record<never, never>>,
    '/FlexGrow': RouteRecordInfo<'/FlexGrow', '/FlexGrow', Record<never, never>, Record<never, never>>,
    '/FlexJustifyContent': RouteRecordInfo<'/FlexJustifyContent', '/FlexJustifyContent', Record<never, never>, Record<never, never>>,
    '/FlexShrink': RouteRecordInfo<'/FlexShrink', '/FlexShrink', Record<never, never>, Record<never, never>>,
    '/FlexWrap': RouteRecordInfo<'/FlexWrap', '/FlexWrap', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
  }
}
