/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    FancyList: typeof import('./src/components/FancyList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyComponent: typeof import('./src/components/MyComponent.vue')['default']
    NDateInput: typeof import('./src/components/NDateInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScopedSlotComponent: typeof import('./src/components/ScopedSlotComponent.vue')['default']
    SubmitButton: typeof import('./src/components/SubmitButton.vue')['default']
    ToDoCard: typeof import('./src/components/ToDoCard.vue')['default']
    ToDoList: typeof import('./src/components/ToDoList.vue')['default']
  }
}
