/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404Page': RouteRecordInfo<'/404Page', '/:pathMatch(.*)*', Record<never, never>, Record<never, never>>,
    '/Gsap404Page': RouteRecordInfo<'/Gsap404Page', '/:pathMatch(.*)*', Record<never, never>, Record<never, never>>,
    '/AxiosGet': RouteRecordInfo<'/AxiosGet', '/AxiosGet', Record<never, never>, Record<never, never>>,
    '/CreateToDo': RouteRecordInfo<'/CreateToDo', '/CreateToDo', Record<never, never>, Record<never, never>>,
    '/CssAnimation': RouteRecordInfo<'/CssAnimation', '/CssAnimation', Record<never, never>, Record<never, never>>,
    '/CssTransition': RouteRecordInfo<'/CssTransition', '/CssTransition', Record<never, never>, Record<never, never>>,
    '/CustomTransitionClass': RouteRecordInfo<'/CustomTransitionClass', '/CustomTransitionClass', Record<never, never>, Record<never, never>>,
    '/DynamicSlotName': RouteRecordInfo<'/DynamicSlotName', '/DynamicSlotName', Record<never, never>, Record<never, never>>,
    '/GsapFromTo': RouteRecordInfo<'/GsapFromTo', '/GsapFromTo', Record<never, never>, Record<never, never>>,
    '/item/[itemid]': RouteRecordInfo<'/item/[itemid]', '/item/:itemid', { itemid: ParamValue<true> }, { itemid: ParamValue<false> }>,
    '/LoginAccount': RouteRecordInfo<'/LoginAccount', '/LoginAccount', Record<never, never>, Record<never, never>>,
    '/Modifiers': RouteRecordInfo<'/Modifiers', '/Modifiers', Record<never, never>, Record<never, never>>,
    '/NamedScopedSlot': RouteRecordInfo<'/NamedScopedSlot', '/NamedScopedSlot', Record<never, never>, Record<never, never>>,
    '/NamedSlot': RouteRecordInfo<'/NamedSlot', '/NamedSlot', Record<never, never>, Record<never, never>>,
    '/NestedTransition': RouteRecordInfo<'/NestedTransition', '/NestedTransition', Record<never, never>, Record<never, never>>,
    '/ParentComponent': RouteRecordInfo<'/ParentComponent', '/ParentComponent', Record<never, never>, Record<never, never>>,
    '/ProfileAccount': RouteRecordInfo<'/ProfileAccount', '/ProfileAccount', Record<never, never>, Record<never, never>>,
    '/RegisterAccount': RouteRecordInfo<'/RegisterAccount', '/RegisterAccount', Record<never, never>, Record<never, never>>,
    '/ScopedSlot': RouteRecordInfo<'/ScopedSlot', '/ScopedSlot', Record<never, never>, Record<never, never>>,
    '/SlideTransition': RouteRecordInfo<'/SlideTransition', '/SlideTransition', Record<never, never>, Record<never, never>>,
    '/SlotContent': RouteRecordInfo<'/SlotContent', '/SlotContent', Record<never, never>, Record<never, never>>,
    '/TransitionBasic': RouteRecordInfo<'/TransitionBasic', '/TransitionBasic', Record<never, never>, Record<never, never>>,
    '/TransitionDuration': RouteRecordInfo<'/TransitionDuration', '/TransitionDuration', Record<never, never>, Record<never, never>>,
    '/TransitionElements': RouteRecordInfo<'/TransitionElements', '/TransitionElements', Record<never, never>, Record<never, never>>,
    '/TransitionGroupExam1': RouteRecordInfo<'/TransitionGroupExam1', '/TransitionGroupExam1', Record<never, never>, Record<never, never>>,
    '/TransitionGroupExam2': RouteRecordInfo<'/TransitionGroupExam2', '/TransitionGroupExam2', Record<never, never>, Record<never, never>>,
    '/TransitionGroupExam3': RouteRecordInfo<'/TransitionGroupExam3', '/TransitionGroupExam3', Record<never, never>, Record<never, never>>,
    '/TransitionGsap': RouteRecordInfo<'/TransitionGsap', '/TransitionGsap', Record<never, never>, Record<never, never>>,
    '/TransitionHooks': RouteRecordInfo<'/TransitionHooks', '/TransitionHooks', Record<never, never>, Record<never, never>>,
  }
}
